const data =
[
    {
    codigo: 1,
    imagem1: 'produto001.webp',
    imagem2:  'produto001-b.webp' ,
    nome: 'Perfume Masculino V - Eau de Parfum 100ml',
    preco: '310',
    volume: '100ml',
    material: '',
    cor: 'preto',
    largura: '',
    espessura: '',
    classificacao: '',
    tipo: ['acessorios', 'masculino'],
    garantia: '3 meses'
},
{
    codigo: 2,
    imagem1: 'produto001.webp',
    imagem2:  'produto001-b.webp' ,
    nome: 'Perfume Masculino V - Eau de Parfum 100ml',
    preco: '310',
    volume: '100ml',
    material: '',
    cor: 'preto',
    largura: '',
    espessura: '',
    classificacao: '',
    tipo: ['acessorios', 'masculino'],
    garantia: '3 meses'
},
{
    codigo: 3,
    imagem1: 'produto001.webp',
    imagem2:  'produto001-b.webp' ,
    nome: 'Perfume Masculino V - Eau de Parfum 100ml',
    preco: '310',
    volume: '100ml',
    material: '',
    cor: 'preto',
    largura: '',
    espessura: '',
    classificacao: '',
    tipo: ['acessorios', 'masculino'],
    garantia: '3 meses'
},
{
    codigo: 4,
    imagem1: 'produto001.webp',
    imagem2:  'produto001-b.webp' ,
    nome: 'Perfume Masculino V - Eau de Parfum 100ml',
    preco: '310',
    volume: '100ml',
    material: '',
    cor: 'preto',
    largura: '',
    espessura: '',
    classificacao: '',
    tipo: ['acessorios', 'masculino'],
    garantia: '3 meses'
},
{
    codigo: 5,
    imagem1: 'produto001.webp',
    imagem2:  'produto001-b.webp' ,
    nome: 'Perfume Masculino V - Eau de Parfum 100ml',
    preco: '310',
    volume: '100ml',
    material: '',
    cor: 'preto',
    largura: '',
    espessura: '',
    classificacao: '',
    tipo: ['acessorios', 'masculino'],
    garantia: '3 meses'
},
{
    codigo: 6,
    imagem1: 'produto001.webp',
    imagem2:  'produto001-b.webp' ,
    nome: 'Perfume Masculino V - Eau de Parfum 100ml',
    preco: '310',
    volume: '100ml',
    material: '',
    cor: 'preto',
    largura: '',
    espessura: '',
    classificacao: '',
    tipo: ['acessorios', 'masculino'],
    garantia: '3 meses'
},

]